---
- name: restart skhd 
  ansible.builtin.command: skhd --restart-service

- name: restart yabai 
  ansible.builtin.command: yabai --restart-service

- name: restart dock
  ansible.builtin.command: killall Dock
