---
- name: install homebrew command line packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cmd_packages }}"
  tags: packages

- name: install homebrew cask packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cask_packages }}"
  tags: packages

- name: install / update vim-hcl syntax plugin (https://github.com/jvirtanen/vim-hcl/tree/master/syntax)
  ansible.builtin.script: "{{ script_common_install_vim_hcl_syntax }}"
  tags: packages

- name: copy common nix configurations
  ansible.builtin.copy: 
    src: "{{ item }}"
    dest: "$HOME/"
  with_items: "{{ common_nix_configs }}"
  tags: configs

- name: copy macOS configurations
  ansible.builtin.copy: 
    src: "{{ item }}"
    dest: "$HOME/"
  with_items: "{{ macos_configs }}"
  tags: configs
  notify:
  - restart brew services

- name: fix ZSH files to avoid compaudit warnings (see https://github.com/zsh-users/zsh-completions/issues/680)
  ansible.builtin.shell: compaudit | xargs chmod g-w
  args:
    executable: /bin/zsh

- name: add all spaces required for yabai + skhd
  ansible.builtin.script: "{{ script_macos_create_spaces }}"
  args:
    executable: osascript
  tags: spaces

- name: disable spaces MRU behavior
  ansible.builtin.shell: |
    defaults write com.apple.dock mru-spaces -bool false
    killall Dock
  tags: spaces
