---
- name: install yabai and skhd
  ansible.builtin.command: brew install {{ item }}
  with_items:
    - koekeishiya/formulae/yabai
    - koekeishiya/formulae/skhd
  tags: packages

- name: install homebrew command line packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cmd_packages }}"
  tags: packages

- name: install homebrew cask packages
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_cask_packages }}"
  tags: packages

- name: install vim-terraform plugin (https://github.com/hashivim/vim-terraform)
  ansible.builtin.script: "{{ script_common_install_vim_terraform_plugin }}"
  tags: packages

- name: copy common nix configurations
  ansible.builtin.copy: 
    src: "{{ item }}"
    dest: "$HOME/"
  with_items: "{{ common_nix_configs }}"
  tags: configs

- name: copy macOS configurations
  ansible.builtin.copy: 
    src: "{{ item }}"
    dest: "$HOME/"
  with_items: "{{ macos_configs }}"
  tags: configs
  notify: 
    - restart skhd
    - restart yabai

- name: fix ZSH files to avoid compaudit warnings (see https://github.com/zsh-users/zsh-completions/issues/680)
  ansible.builtin.shell: compaudit | xargs chmod g-w
  args:
    executable: /bin/zsh

- name: add all spaces required for yabai + skhd
  ansible.builtin.script: "{{ script_macos_create_spaces }}"
  args:
    executable: osascript
  tags: spaces

- name: disable spaces MRU behavior
  ansible.builtin.shell: |
    defaults write com.apple.dock mru-spaces -bool false
  notify: restart dock
  tags: spaces

- name: set keyboard rate repeat settings
  ansible.builtin.shell: |
    defaults write -g InitialKeyRepeat -int 15
    defaults write -g KeyRepeat -int 2
  notify: restart dock
  tags: keyboard
